apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: podtato-server
  template:
    metadata:
      labels:
        app: podtato-server
    spec:
      containers:
      - name: podtato-server
        image: nginx:lastest
        ports:
        - containerPort: 80
