apiVersion appsv1
kind Deployment
metadata
  name aks-helloworld-one 
spec
  replicas 1
  selector
    matchLabels
      app aks-helloworld-one
  template
    metadata
      labels
        app aks-helloworld-one
    spec
      containers
      - name aks-helloworld-one
        image mcr.microsoft.comazuredocsaks-helloworldv1
        ports
        - containerPort 80
        env
        - name TITLE
          value Welcome to Azure Kubernetes Service (AKS) hosted in GAHE